-- Database export via SQLPro (https://www.sqlprostudio.com/)
-- Exported by haridass at 22-09-2026 20:58.
-- WARNING: This file may contain destructive statements such as DROPs.
-- Please ensure that you are running the script at the proper location.


-- BEGIN TABLE public.patient_goals
BEGIN;

CREATE TABLE IF NOT EXISTS public.patient_goals (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	patient_id bigint,
	goal_date date,
	cerv_flex_goal numeric,
	cerv_flex_td date,
	lumbar_ext_goal numeric,
	lumbar_ext_td date,
	sit_stand_goal numeric,
	"sit-stand_td" date,
	PRIMARY KEY(id)
);

COMMIT;

-- END TABLE public.patient_goals

ALTER TABLE IF EXISTS public.patient_goals
	ADD CONSTRAINT patient_fk
	FOREIGN KEY (patient_id)
	REFERENCES public.patients (id);

